#! /bin/sh

#
#                 ░█▀▄░█▀▀░█▀█░█░█░█▄█
#                 ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#                 ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀
#

$HOME/.scripts/custom-autostart

# Network manager
#nm-applet &

xsetroot -cursor_name left_ptr
sxhkd &
picom &
nitrogen --restore
wmname LG3D &
xset -dpms s off & # disable screen blanking
dunst &

xrandr --output HDMI-1 --primary --left-of HDMI-0
#dropbox &
#nautilus --gapplication-service &

# Swallow

#nohup pidof $HOME/.scripts/bspswallow || $HOME/.scripts/bspswallow &
pgrep bspswallow || nohup ~/.scripts/bspswallow &

# Workspaces

bspc config window_gap          20
bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false
$HOME/.config/bspwm/autostart

# Default state/workspace for applications
bspc rule -a mplayer2 state=floating
bspc rule -a nomacs state=floating
bspc rule -a discord state=floating center=on rectangle=1600x900+0+0
bspc rule -a thunderbird state=floating center=on rectangle=1600x900+0+0
bspc rule -a XTerm state=floating
bspc rule -a "Image Lounge" state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config pointer_modifier mod4

#sleep 0.69

# Autostart applications:

# Start Polybar
$HOME/.config/polybar/scripts/launch-polybar.sh &

# Start floating kitty terminal
bspc rule -a \* -o state=floating && sleep 0.015 ; kitty -e $SHELL -c "$HOME/.config/neofetch/launch-neofetch.sh && $SHELL" &

sleep 1.55 

# Start firefox
/bin/bash -c "bspc desktop -f '^2' --follow ; bspc rule -a \* -o node=@$(bspc query -D -d):.focused split_dir=south follow=off ; firefox &" &
bspc desktop -f '^2' --follow &

setxkbmap -layout de
xinput set-prop "SOAI USB Gaming Mouse" "libinput Accel Speed" -0.5
timedatectl&
setxkbmap -option caps:escape # Caps lock -> escape
bashrun2 hide&
